### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by batizhevsky** [capistrano/rvm#28]
cap 3

± cap staging deploy
cap aborted!
undefined method `each' for nil:NilClass
/Users/Leonid/.rvm/gems/ruby-2.0.0-p353@ekster/gems/capistrano-rvm-0.1.0/lib/capistrano/tasks/rvm.rake:38:in`block (2 levels) in <top (required)>'
/Users/Leonid/.rvm/gems/ruby-2.0.0-p353@ekster/gems/capistrano-3.0.1/lib/capistrano/dsl.rb:14:in `invoke'
/Users/Leonid/.rvm/gems/ruby-2.0.0-p353@ekster/gems/capistrano-3.0.1/lib/capistrano/dsl/task_enhancements.rb:11:in`block in after'
/Users/Leonid/.rvm/gems/ruby-2.0.0-p353@ekster/gems/capistrano-3.0.1/lib/capistrano/application.rb:12:in `run'
/Users/Leonid/.rvm/gems/ruby-2.0.0-p353@ekster/gems/capistrano-3.0.1/bin/cap:3:in`<top (required)>'
/Users/Leonid/.rvm/gems/ruby-2.0.0-p353@ekster/bin/cap:23:in `load'

**Comment by kirs** [comment]
Your `rvm_map_bins` is empty, but it supposed to be populated in the `load:defaults` task. Could you try capistrano from upstream?

**Comment by batizhevsky** [comment]
I rollback to 2.x branch. Thank you for help.

**Comment by kirs** [comment]
You're welcome. I don't have any ideas yet why this exception happens in your environment, because `load:defaults` is called here: https://github.com/capistrano/capistrano/blob/eba1b007a11f6aa2ea233c2b9b77a518f2cdff72/lib/capistrano/setup.rb#L13

We would appreciate if your show your capistrano configs so maybe I will find a reason why this issue may happen.
As a workaround, you can try declaring `set :rvm_map_bins, %w{gem rake ruby bundle}` right in your `deploy.rb`.

Please notice that 2.x is not supported anymore.

**Comment by systemiv** [comment]
i have the same problem

**Comment by kirs** [comment]
Could you share your config, please?

**Comment by systemiv** [comment]
https://gist.github.com/systemiv/c8c5338ae9ffb23a579e

**Comment by kirs** [comment]
``` ruby
require 'capistrano/rvm'
require 'capistrano/bundler'
```

Should be placed in Capfile, as it's said in README :)

**Comment by systemiv** [comment]
Oh, please forgive me. Really my fault. thx

**Comment by kirs** [comment]
You're welcome! I'm glad that we solved the issue.
