### ISSUE TITLE
cap production deploy aborted

### ISSUE THREAD

**Issue by KehindeAyanleye** [capistrano/rvm#84]
When I run cap production deploy
 I get the following error

```
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@**.**.**.***: Authentication failed for user deploy@**.**.**.***

Net::SSH::AuthenticationFailed: Authentication failed for user deploy@**.**.**.***

Tasks: TOP => rvm:check
(See full trace by running task with --trace)
```

**Comment by will-in-wi** [comment]
It looks like this has nothing to do with RVM and is an issue with logging into your server as the deploy user. Double-check your SSH configuration, and make sure you can SSH into the server.

---

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md). Thanks!

**Comment by KehindeAyanleye** [comment]
Thanks
